# Generated by Django 5.1.2 on 2024-10-28 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etherscan_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_hash",
                    models.CharField(max_length=66, primary_key=True, serialize=False),
                ),
                ("block_number", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                ("from_address", models.CharField(max_length=42)),
                ("to_address", models.CharField(max_length=42)),
                ("value", models.DecimalField(decimal_places=8, max_digits=20)),
                ("gas_used", models.IntegerField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="etherscan_app.address",
                    ),
                ),
            ],
        ),
    ]
