# Generated by Django 5.1.2 on 2024-10-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etherscan_app", "0002_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="balance",
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
    ]
