# Generated by Django 5.1.2 on 2024-10-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etherscan_app", "0003_address_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="last_block_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
